add new adatptor doc
intel/neural-compressor pull request #1035
Opened 2023-06-24 03:30 UTC by ClarkChin08

## Type of Change

Doc add new backend

## Description

add new backend of how to add new adaptor

## How has this PR been tested?

Spelling typo

2023-06-25 01:15 UTC, kevinintel commented on docs/source/add_new_adaptor.md
> +## Introduction
please point out why you should write thsi document.

2023-06-25 01:15 UTC, kevinintel commented on docs/source/add_new_adaptor.md
> +The document outlines the process of adding support for a new adaptor, in Intel® Neural Compressor with minimal changes. It provides instructions and code examples for implementation of a new backend
It's better to move to top

2023-06-25 01:18 UTC, kevinintel requested changes
please refine it

2023-06-26 07:13 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +How to Support New Adaptor
'support' to 'add an'

2023-06-26 07:16 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +The diagram below illustrates all the relevant steps of how adaptor is invoked, with additional details provided for each annotated step.
we should introduce what's the interface in adaptor layer at first, and then the working flow how they interactive each other

2023-06-26 07:18 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +1. **Strategy**: Drives the overall tuning process and utilizes `adaptor.query_fw_capability` to query the framework's capabilities.
there are a lots of `strategy` words here. the organization is NOT straightforward, at least for me.

2023-06-26 07:22 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +        # loop over the model and generate the capability of the model
this code snippet is also not easy to understand, such as where the quantiable_op_details variable comes from? whether it's the whole code or just partial of code? should use `...` to present those skipped code?

2023-06-26 07:26 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +self.quantize_config  = {
maybe integrate with working flow is better? I think here is used to describe what's the input format of the quantize() func in adaptor, right?

2023-06-26 07:27 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +### Insert FakeQuant operator to the fp32 graph for calibration.
this is keras specific implementation, maybe you can skip this?

2023-06-27 03:56 UTC, chensuyue commented
Please clean the CI issue, add reasonable words into https://github.com/intel/neural-compressor/blob/add_new_backend/.azure-pipelines/scripts/codeScan/pyspelling/inc_dict.txt

2023-06-29 01:47 UTC, chensuyue commented
@ClarkChin08 please take a look at the comments.

2023-06-29 08:39 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +1. **Adaptor**: Design the framework YAML, inherit `QueryBackendCapability` class to parse the framework yaml.
still like what I mentioned, this index + *Adaptor* is not a good way to describe what happens in the diagram. 

is it better to use ① like symbol and skip the first word like **adaptor**?

2023-06-29 08:40 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +| query_fw_capability(self, model) | **model** (object): A INC model object to query quantization tuning capability. | The function is used to return framework tuning capability. |Confirm the the dat
what's the output of such funcs? could you pls add?

2023-06-29 08:41 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +        # loop over the model and generate the capability of the model
you didn't solve my concerns.

I think the doc is too complex and expose too much internals to user like the explanation on `quantizable_op_details`

2023-06-30 07:21 UTC, ftian1 approved these changes
most are ok to me. just minor comments

2023-06-30 07:21 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +| get_optype_wise_ability(self, quantizable_op_details) | **quantizable_op_details** (string dict): the key is op type while the value is the detail configurations of activation and weight for this o
shall we remove this line as it doesn't need to be aware by user?

2023-06-30 07:21 UTC, ftian1 commented on docs/source/add_new_adaptor.md
> +| tuning_cfg_to_fw(self, tuning_cfg) | **tuning_cfg** (string dict): Tuning config generated . |None| The function is used in quantize API and transfer the chosen tuning config to self.quantize_confi
it looks more like internal implementation but not the interface user needs to be aware of

2023-07-03 04:03 UTC, merged