add sparseGPT pruner feature, refactor pruning class
intel/neural-compressor pull request #1111
Opened 2023-07-23 13:48 UTC by WeiweiZhang1

## Type of Change

feature
API not changed

## Description

refactor sparseGPT and retrain-free, add two new post-training pruning class.

2023-07-25 01:22 UTC, n1ck-guo approved these changes

2023-07-25 01:51 UTC, wenhuach21 commented on neural_compressor/compression/pruner/pruners/sparse_gpt.py
> +        def __init__(self, module):
add reference paper later

2023-07-25 01:52 UTC, wenhuach21 commented on neural_compressor/compression/pruner/pruning.py
> +    Args:
merge experimental/pruning.py later

2023-07-25 01:53 UTC, wenhuach21 commented on neural_compressor/compression/pruner/pruning.py
> +        :return: A list of pruner
need to support inc prepare_compression later, I don't see  any change for this part

2023-07-25 02:00 UTC, wenhuach21 commented on neural_compressor/compression/pruner/pruning.py
> +        if torch.cuda.is_available():
get the device from model

2023-07-25 02:13 UTC, wenhuach21 commented on neural_compressor/compression/pruner/pruning.py
> +                 dataloader: torch.utils.data.DataLoader,
remove the type from dataloader, users could customize their own

2023-07-25 02:22 UTC, wenhuach21 commented on neural_compressor/compression/pruner/__init__.py
> +                    loss_func=None, framework='pytorch', device: str ='cuda:0'):
delete the device from the function

2023-07-25 02:27 UTC, wenhuach21 commented on neural_compressor/compression/pruner/__init__.py
> +                    opt_or_dataloader: Union[torch.optim.Optimizer, torch.utils.data.DataLoader],
if the model is limited to torch.nn.module, why do we need a framework parameter? better detect the framework automatically

2023-07-25 02:34 UTC, wenhuach21 requested changes
The current code is not suitable to support prepare_comperssion.

2023-07-31 01:59 UTC, wenhuach21 approved these changes

2023-07-31 07:59 UTC, chensuyue commented
We can merge this PR first, please submit another PR to update docs including 1. example readme，2. example list, 3. pruning feature docs.

2023-07-31 08:00 UTC, merged