Add bias for fx_model
intel/neural-compressor pull request #1447
Opened 2023-12-06 11:11 UTC by Kaihui-intel

## Type of Change

bug fix

## Description

AttributeError: 'GraphModule' object has no attribute 'bias' - GeoLayutLM model
fix issue [1416](https://github.com/intel/neural-compressor/issues/1416)

## Expected Behavior & Potential Risk

## How has this PR been tested?

Pre-CI

## Dependency Change?

None

2023-12-06 13:21 UTC, chensuyue commented
target v2.4rc2?

2023-12-07 01:34 UTC, xin3he requested changes
misssing check `not isinstance(fx_model.module.weight, torch.Tensor)`

2023-12-11 12:32 UTC, xin3he approved these changes

2023-12-12 01:23 UTC, XuehaoSun approved these changes

2023-12-12 01:24 UTC, merged