add docstring for static quant and smooth quant
intel/neural-compressor pull request #1936
Opened 2024-07-18 06:08 UTC by violetch24

## Type of Change

docstring

## Description

add docstring for static quant and smooth quant

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

2024-07-18 06:16 UTC, yiliu30 requested changes
As the docstring CI didn't include these files, please check them locally. 
```bash
pydocstyle --convention=google ./neural_compressor/torch/algorithms/static_quant/
pydocstyle --convention=google ./neural_compressor/torch/algorithms/smooth_quant/
```

2024-07-18 10:31 UTC, yiliu30 commented
Please update the scan path. 

https://github.com/intel/neural-compressor/blob/master/.azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt

2024-07-19 07:08 UTC, yiliu30 approved these changes

2024-07-19 07:12 UTC, xin3he approved these changes

2024-07-19 07:56 UTC, merged