Add Docstring for TF 3x API
intel/neural-compressor pull request #1944
Opened 2024-07-23 06:47 UTC by zehao-intel

## Type of Change

 documentation

## Description

Add Docstring for TF 3x API

## How has this PR been tested?

PreCI

## Dependency Change?

No

2024-07-23 07:09 UTC, yiliu30 requested changes
Please update the scan path.

https://github.com/intel/neural-compressor/blob/master/.azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt

2024-07-23 07:29 UTC, zehao-intel commented
> Please update the scan path.
> 
> https://github.com/intel/neural-compressor/blob/master/.azure-pipelines/scripts/codeScan/pydocstyle/scan_path.txt

Added

2024-07-23 07:51 UTC, yiliu30 approved these changes

2024-07-25 05:38 UTC, chensuyue approved these changes

2024-07-25 05:39 UTC, merged