Doc: Update readme.md
intel/neural-compressor pull request #2083
Opened 2024-12-04 07:15 UTC by feng-intel

## Type of Change

feature or bug fix or documentation or validation or others  
API changed or not

## Description

detail description

## Expected Behavior & Potential Risk

the expected behavior that triggered by this PR 

## How has this PR been tested?

how to reproduce the test (including hardware information)

## Dependency Change?

any library dependency introduced or removed

2024-12-16 14:40 UTC, thuang6 commented on docs/source/3x/PT_FP8Quant.md
> +BF16 KVCache Code -> [Modeling_all_models.py -> KVCache()](https://github.com/huggingface/optimum-habana/blob/main/optimum/habana/transformers/models/modeling_all_models.py#L40)
not be good to link to certain line of code which is subject to change.  may explain some general idea or link to certain doc in OH

2024-12-16 14:43 UTC, thuang6 commented on docs/source/3x/PT_FP8Quant.md
> +### FP8 Accuracy
this acc data is not right and not update-to-date.  please check with @XuehaoSun for latest test result.  For Qwen2.5 model, there is bug opened, you can wait for that get fixed.

2024-12-16 14:53 UTC, thuang6 commented on docs/source/3x/PT_FP8Quant.md
> +### FP8 KV cache
enable PatchedVLLMKVCache is not enough.  recent PR:  https://github.com/HabanaAI/vllm-fork/pull/569 enabled INC to patch ModuleFusedSDPA to FP8.  without this PR, there is no perf gain in attention from FP8 KV cache

2024-12-17 05:16 UTC, xin3he commented on docs/source/3x/PT_FP8Quant.md
> +| `Llama-2-7b-hf`| fp8 & fp8 KVCache| bf16 w/o fp8 KVCache|
bf16 w/o fp8 KVCache? -> `bf16 w/ bf16 KVCache` or `bf16 w/o bf16 KVCache`

2024-12-17 05:25 UTC, xin3he reviewed
`vllm_gaudi.png` is pretty good, I notice two typos.
- The model path in command is your local path. 
- `import neural_compressor.torch.quantization` is missing '.', same to vllm_hpu_extension

2024-12-17 05:45 UTC, chensuyue commented on README.md
> +[Install intel_extension_for_pytorch for CPU -> Installation](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/)
Please remove ` -> Installation`, it looks not good.

2024-12-17 05:46 UTC, chensuyue commented on README.md
> +[Use Docker Image with torch installed for HPU](https://docs.habana.ai/en/latest/Installation_Guide/Bare_Metal_Fresh_OS.html#bare-metal-fresh-os-single-click)    --> **Note**: There is a version mapp
Remove `--> `, put **Note** in a new line.

2024-12-17 05:47 UTC, chensuyue commented on README.md
> +[Install Tensorflow](https://www.tensorflow.org/install)
tensorflow or TensorFlow.

2024-12-17 05:49 UTC, chensuyue commented on README.md
>  ### Install Framework
Maybe add some description for this session, like "Choose the necessary framework dependencies to install based on your deploy environment. "

2024-12-17 05:53 UTC, chensuyue commented on README.md
> +pip install -r requirements.txt
For 3x torch, no need this line `pip install -r requirements.txt`.

2024-12-20 01:49 UTC, xin3he approved these changes
LGTM

2024-12-24 07:21 UTC, chensuyue commented on README.md
> +[Install intel_extension_for_pytorch for CPU](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/)
Need to split those into several lines, make it clearer. 
![image](https://github.com/user-attachments/assets/917e971e-dd61-49f6-8a20-cd3745c7f17d)

2024-12-24 07:23 UTC, chensuyue commented on README.md
> +[Install intel_extension_for_pytorch for CPU](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/)
- [Install intel_extension_for_pytorch for CPU](https://intel.github.io/intel-extension-for-pytorch/cpu/latest/) 
- [Install intel_extension_for_pytorch for XPU](https://intel.github.io/intel-extension-for-pytorch/xpu/latest/) 
- [Use Docker Image with torch installed for HPU](https://docs.habana.ai/en/latest/Installation_Guide/Bare_Metal_Fresh_OS.html#bare-metal-fresh-os-single-click)
Note: There is a version mapping between Intel Neural Compressor and Gaudi Software Stack, please refer to this [table](https://github.com/intel/neural-compressor/blob/e0b65444535a3ce502b2cf5c65921dfa29786dd0/docs/source/3x/gaudi_version_map.md) and make sure to use a matched combination.
- [Install torch for other platform](https://pytorch.org/get-started/locally)
- [Install tensorflow](https://www.tensorflow.org/install)

2024-12-24 13:22 UTC, xin3he requested changes

2024-12-24 13:22 UTC, xin3he commented on docs/source/3x/PT_FP8Quant.md
> +| `Llama-2-7b-hf`| fp8 & fp8 KVCache| bf16 w/ fp16 KVCache|
```suggestion
| `Llama-2-7b-hf`| fp8 & fp8 KVCache| bf16 w/ bf16 KVCache|
```

2024-12-24 13:22 UTC, xin3he commented on docs/source/3x/PT_FP8Quant.md
> +| `Qwen2.5-7B-Instruct`| fp8 & fp8 KVCache| bf16 w/ fp16 KVCache|
same

2024-12-24 13:22 UTC, xin3he commented on docs/source/3x/PT_FP8Quant.md
> +| `Llama-3.1-8B-Instruct`| fp8 & fp8 KVCache| bf16 w/ fp16 KVCache|
same

2024-12-24 13:22 UTC, xin3he commented on docs/source/3x/PT_FP8Quant.md
> +| `Mixtral-8x7B-Instruct-v0.1`| fp8 & fp8 KVCache| bf16 w/ fp16 KVCache||
same

2024-12-30 02:16 UTC, XuehaoSun commented
/azp run Model-Test,UT-3x-TensorFlow,UT-3x-Torch,UT-Basic

2024-12-30 02:58 UTC, XuehaoSun commented
/azp run Model-Test,UT-3x-TensorFlow,UT-3x-Torch,UT-Basic

2024-12-31 03:58 UTC, chensuyue approved these changes

2025-01-02 01:37 UTC, xin3he approved these changes

2025-01-02 01:41 UTC, XuehaoSun commented
/azp run Model-Test,UT-3x-TensorFlow,UT-3x-Torch,UT-Basic

2025-01-02 01:56 UTC, merged