add block_mask & retrain_free features
intel/neural-compressor pull request #775
Opened 2023-03-30 15:33 UTC by WeiweiZhang1

## Type of Change
Pruning Features and Bugfix

## Details
add block_mask & retrain_free pruning-types
fixed the pattern Initialization problem and the problem of substandard sparsity.
add feature related LLM model pruning and slim example and test-units.

API not changed

2023-04-10 10:08 UTC, wenhuach21 commented on neural_compressor/compression/pruner/criteria.py
> +                mask_grad = self.modules[key].block_mask.grad.clone()
don't forget to remove the clone

2023-04-10 10:08 UTC, wenhuach21 commented on neural_compressor/compression/pruner/criteria.py
> +                self.collected_grads[key].append(mask_grad)
why not use +, append will cost much more memory

2023-04-10 10:09 UTC, wenhuach21 commented on neural_compressor/compression/pruner/pruners.py
> +                module.block_mask.data = masks[key].data.clone()
please review all the clone operation to check whether it is a must

2023-04-10 10:15 UTC, wenhuach21 commented on neural_compressor/compression/pruner/criteria.py
> +        self.alpha = 1.0
why set alpha=1.0

2023-04-10 13:15 UTC, wenhuach21 commented on examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_clm_no_trainer.py
> +        accuracy, avg_latency = eval_func(model)
move these 3 lines out of auto_slim

2023-04-11 08:58 UTC, YIYANGCAI approved these changes

2023-04-11 08:58 UTC, YIYANGCAI commented on examples/pytorch/nlp/huggingface_models/language-modeling/pruning/eager/run_llm_pruning.sh
replace path with string like "/path/to/your/model" will be easier to understand.

2023-04-11 09:27 UTC, wenhuach21 requested changes

2023-04-11 09:27 UTC, wenhuach21 commented on neural_compressor/compression/pruner/pruners.py
> +            return F.linear(input, self.weight*mask, self.bias)
layer could be convolution

2023-04-11 09:29 UTC, wenhuach21 commented on neural_compressor/compression/pruner/pruners.py
>              config['criterion_type'] = name
have you check edthat blockwise criterion only supports NXM

2023-04-11 10:18 UTC, wenhuach21 approved these changes
need to support conv2d later

2023-04-12 02:58 UTC, merged