Fixed the wrong description
intel/neural-compressor pull request #777
Opened 2023-03-31 05:30 UTC by PenghuiCheng

## Type of Change

documentation
No API changed

## Description

Doc enhancement

2023-03-31 07:02 UTC, ftian1 requested changes

2023-03-31 07:02 UTC, ftian1 commented on neural_compressor/training.py
> +        confs (Union[Callable, List]): The instance of QuantizationAwareTrainingConfig,
the comment is still wrong

2023-03-31 07:02 UTC, ftian1 commented on neural_compressor/training.py
> +        confs (Union[Callable, List]): The instance of QuantizationAwareTrainingConfig,
I meant the quantization.py comment is wrong.

2023-04-05 13:48 UTC, chensuyue approved these changes

2023-04-05 13:49 UTC, merged