Fix for layernorm skip connections in sq
intel/neural-compressor pull request #962
Opened 2023-06-09 19:34 UTC by maktukmak

## Type of Change

Bug fix

## Description

When folding is enabled in Smoothquant, layer norms are used as absorbing layers for linear layers. However, when there are skip connections from the layer_norms, i.e., the output of layer norm goes to multiple ops, smoothquant quant transform produces wrong results. 

An example graph is shown below:

![image](https://github.com/intel/neural-compressor/assets/31421551/759317ec-2fcc-46ef-b729-6f96370e94a2)

which occurs in the BridgeTower model. This PR checks if any layer norm ops have multiple children, in which case, it is not used as absorbing layer.

## Expected Behavior & Potential Risk

Smoothquant transform won't produce incorrect results when an absorb layer norm has skip connections

## Dependency Change?

This PR works best after applying the following PRs: #961 and #954

2023-06-12 01:09 UTC, xin3he approved these changes

2023-06-12 02:51 UTC, chensuyue commented
Please fix DCO and Pylint scan.

2023-06-14 04:24 UTC, wenhuach21 approved these changes

2023-06-14 06:44 UTC, wenhuach21 requested changes

2023-06-14 06:44 UTC, wenhuach21 commented on neural_compressor/adaptor/torch_utils/smooth_quant.py
> +                    set_inp_type = set(dict_inp[parent])
the code has some issues. We should check output nodes of  the parent

2023-06-14 06:45 UTC, wenhuach21 requested changes

2023-06-14 06:45 UTC, wenhuach21 commented on neural_compressor/adaptor/torch_utils/smooth_quant.py
> +            inp_list = list(node.inputs())
we should check the node's output

2023-06-14 06:54 UTC, yintong-lu reviewed
Hi, I think there's a mistake when you are creating dict_inp. The input-types of all nodes are saved rather than the output-type.

2023-06-15 05:24 UTC, chensuyue commented
Hi @maktukmak, since there are some issues in this PR, we submit a new PR to fix this bug, https://github.com/intel/neural-compressor/pull/1000. So I am going to close this one. Thanks for your submission!

2023-06-15 05:25 UTC, closed without merging